# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ws_backend.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ws_backend.proto\x12\nws_backend\">\n\x14SendTimestampRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"\'\n\x15SendTimestampResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\";\n\x13RemoveAccessRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\"&\n\x14RemoveAccessResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x13\n\x11GetUpdatesRequest\"\x7f\n\x12GetUpdatesResponse\x12\x36\n\x03res\x18\x03 \x03(\x0b\x32).ws_backend.GetUpdatesResponse.DocUpdates\x1a\x31\n\nDocUpdates\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0e\n\x06update\x18\x02 \x03(\t\"*\n\x13HandleDeleteRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\"&\n\x14HandleDeleteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xe5\x02\n\x12WS_Backend_Service\x12V\n\rSendTimestamp\x12 .ws_backend.SendTimestampRequest\x1a!.ws_backend.SendTimestampResponse\"\x00\x12S\n\x0cRemoveAccess\x12\x1f.ws_backend.RemoveAccessRequest\x1a .ws_backend.RemoveAccessResponse\"\x00\x12M\n\nGetUpdates\x12\x1d.ws_backend.GetUpdatesRequest\x1a\x1e.ws_backend.GetUpdatesResponse\"\x00\x12S\n\x0cHandleDelete\x12\x1f.ws_backend.HandleDeleteRequest\x1a .ws_backend.HandleDeleteResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ws_backend_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENDTIMESTAMPREQUEST._serialized_start=32
  _SENDTIMESTAMPREQUEST._serialized_end=94
  _SENDTIMESTAMPRESPONSE._serialized_start=96
  _SENDTIMESTAMPRESPONSE._serialized_end=135
  _REMOVEACCESSREQUEST._serialized_start=137
  _REMOVEACCESSREQUEST._serialized_end=196
  _REMOVEACCESSRESPONSE._serialized_start=198
  _REMOVEACCESSRESPONSE._serialized_end=236
  _GETUPDATESREQUEST._serialized_start=238
  _GETUPDATESREQUEST._serialized_end=257
  _GETUPDATESRESPONSE._serialized_start=259
  _GETUPDATESRESPONSE._serialized_end=386
  _GETUPDATESRESPONSE_DOCUPDATES._serialized_start=337
  _GETUPDATESRESPONSE_DOCUPDATES._serialized_end=386
  _HANDLEDELETEREQUEST._serialized_start=388
  _HANDLEDELETEREQUEST._serialized_end=430
  _HANDLEDELETERESPONSE._serialized_start=432
  _HANDLEDELETERESPONSE._serialized_end=470
  _WS_BACKEND_SERVICE._serialized_start=473
  _WS_BACKEND_SERVICE._serialized_end=830
# @@protoc_insertion_point(module_scope)
